### ISSUE TITLE
Failed to install in RStudio

### ISSUE THREAD

**Issue by OscarLecuona** [PsyTeachR/introdataviz#5]
The install command throws an error:
> devtools::install_github("psyteachr/introdataviz")
Downloading GitHub repo psyteachr/introdataviz@HEAD
Error: Failed to install 'introdataviz' from GitHub:
  Missing commas separating Remotes: 'psyteachr/glossary
    crsh/papaja'

**Comment by debruine** [comment]
Should be fixed now, thanks!!

**Comment by OscarLecuona** [comment]
thanks! works fine now!
